server:
  port: 8989 #指定端口
  servlet:
    context-path: /SystemKyujin  #制定项目名
    jsp:
      init-parameters:
        development: true   #开启jsp模板的开发模式
#配置jsp模板
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: info
    password: pro
#配置mybatis
mybatis:
  mapper-locations: classpath:com/example/mapper/*.xml
  type-aliases-package: com.example.entity
#配置日志的使用
logging:
  level:
    root: info
    com.example: debug  #指定包日志
